### ISSUE TITLE
Javascript crash

### ISSUE THREAD

**Issue by Widdershin** [Widdershin/powerpeople#28]
```
TypeError: Cannot read property 'joined_powershop_recently?' of undefined
    at s (https://powershop-people.herokuapp.com/assets/application-87209850ce90ab836ebffe437c9c791a3641fa4b8afa9fd3cfff8d95f8a0e54d.js:27:7703)
    at o (https://powershop-people.herokuapp.com/assets/application-87209850ce90ab836ebffe437c9c791a3641fa4b8afa9fd3cfff8d95f8a0e54d.js:27:7449)
    at https://powershop-people.herokuapp.com/assets/application-87209850ce90ab836ebffe437c9c791a3641fa4b8afa9fd3cfff8d95f8a0e54d.js:27:3813
    at Array.map (native)
    at r (https://powershop-people.herokuapp.com/assets/application-87209850ce90ab836ebffe437c9c791a3641fa4b8afa9fd3cfff8d95f8a0e54d.js:27:3788)
    at https://powershop-people.herokuapp.com/assets/application-87209850ce90ab836ebffe437c9c791a3641fa4b8afa9fd3cfff8d95f8a0e54d.js:1932:1364
    at r.next (https://powershop-people.herokuapp.com/assets/application-87209850ce90ab836ebffe437c9c791a3641fa4b8afa9fd3cfff8d95f8a0e54d.js:1934:9936)
    at r.Ve.internals.AbstractObserver.e.onNext (https://powershop-people.herokuapp.com/assets/application-87209850ce90ab836ebffe437c9c791a3641fa4b8afa9fd3cfff8d95f8a0e54d.js:1933:220)
    at r.<anonymous> (https://powershop-people.herokuapp.com/assets/application-87209850ce90ab836ebffe437c9c791a3641fa4b8afa9fd3cfff8d95f8a0e54d.js:1932:1364)
    at e.n.next (https://powershop-people.herokuapp.com/assets/application-87209850ce90ab836ebffe437c9c791a3641fa4b8afa9fd3cfff8d95f8a0e54d.js:1936:4736)
```

**Comment by Widdershin** [comment]
Fixed (don't delete data out of prod kids)
